[package]
name = "rthybrid-komendantov-kononenko-1996-neuron"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rtsyn_plugin = { path = "../../rtsyn-plugin" }
serde_json = "1"

[build-dependencies]
cc = "1"
